// app/layout.js
// import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import Link from "next/link";
export const metadata = {
  title: "Decision Making Payment",
  description: "Generated by Bayan Tech",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <header>
          <h1>Decision Making Payment System</h1>
          <nav>
            <a href="/questions">Questions</a>
            <a href="/projects">Projects</a>
            <a href="/users/login">Login</a>
          </nav>
        </header> */}
        <main>{children}</main>
      </body>
    </html>
  );
}
